# Mock data for Phase 1 - This will be replaced by database/scraping later

PRODUCT_DATA = [
    {
        "id": 1,
        "store": "Amazon",
        "emoji": "🛒",
        "storeType": "Global Marketplace",
        "price": 114900,
        "originalPrice": 129900,
        "discount": 12,
        "rating": 4.6,
        "reviewCount": 18420,
        "delivery": "Free delivery by Tomorrow",
        "cashback": "Up to ₹3,000 cashback (HDFC)",
        "availability": "In Stock",
        "trend": "down",
        "trendText": "↓ 3.2% this week",
        "badges": ["best-deal", "lowest"],
        "isBestDeal": True,
        "buyUrl": "#"
    },
    {
        "id": 2,
        "store": "Flipkart",
        "emoji": "🏪",
        "storeType": "Indian E-commerce",
        "price": 116499,
        "originalPrice": 129900,
        "discount": 10,
        "rating": 4.5,
        "reviewCount": 24312,
        "delivery": "Free delivery in 2 days",
        "cashback": "5% unlimited cashback (Axis)",
        "availability": "In Stock",
        "trend": "down",
        "trendText": "↓ 1.8% this week",
        "badges": ["sale"],
        "isBestDeal": False,
        "buyUrl": "#"
    },
    {
        "id": 3,
        "store": "Apple Store",
        "emoji": "🍎",
        "storeType": "Official Retailer",
        "price": 129900,
        "originalPrice": 129900,
        "discount": 0,
        "rating": 4.9,
        "reviewCount": 8724,
        "delivery": "Free same-day delivery (select cities)",
        "cashback": "3% Daily Cash with Apple Card",
        "availability": "In Stock",
        "trend": "stable",
        "trendText": "→ No change",
        "badges": ["official"],
        "isBestDeal": False,
        "buyUrl": "#"
    },
    {
        "id": 4,
        "store": "Croma",
        "emoji": "🏬",
        "storeType": "Electronics Retail",
        "price": 119990,
        "originalPrice": 129900,
        "discount": 8,
        "rating": 4.3,
        "reviewCount": 3621,
        "delivery": "Free delivery in 3–4 days",
        "cashback": "10% off on Tata Neu Pay",
        "availability": "Limited Stock (3 left)",
        "trend": "stable",
        "trendText": "→ Stable this week",
        "badges": [],
        "isBestDeal": False,
        "buyUrl": "#"
    },

    {
        "id": 6,
        "store": "Reliance Digital",
        "emoji": "📱",
        "storeType": "Digital Retail",
        "price": 123000,
        "originalPrice": 129900,
        "discount": 5,
        "rating": 4.1,
        "reviewCount": 2140,
        "delivery": "Delivery in 5 days",
        "cashback": "₹2,000 off on exchange",
        "availability": "Out of Stock Online",
        "trend": "down",
        "trendText": "↓ 2.1% this week",
        "badges": [],
        "isBestDeal": False,
        "buyUrl": "#"
    }
]

ALERTS_DATA = [
    {
        "id": 1,
        "type": "positive",
        "icon": "📉",
        "product": "iPhone 16 Pro · 256GB",
        "title": "Price Dropped 12% on Amazon!",
        "message": "Amazon just reduced the iPhone 16 Pro price from ₹1,29,900 to ₹1,14,900. This is the lowest price in the last 6 months.",
        "store": "Amazon",
        "time": "2 min ago",
        "action": "View Deal"
    },
    {
        "id": 2,
        "type": "info",
        "icon": "🎯",
        "product": "MacBook Air M3 · 8GB",
        "title": "Best Buying Window Detected",
        "message": "AI analysis shows that the next 72 hours are the optimal buying window for MacBook Air M3 based on seasonal patterns.",
        "store": "Flipkart",
        "time": "18 min ago",
        "action": "Check Price"
    },
    {
        "id": 3,
        "type": "warning",
        "icon": "📈",
        "product": "Sony WH-1000XM5",
        "title": "Price Surge Warning — Act Fast!",
        "message": "Sony WH-1000XM5 headphones are predicted to increase by ₹3,000–₹4,000 within 2 weeks due to festive demand.",
        "store": "Multiple Stores",
        "time": "1 hr ago",
        "action": "Buy Now"
    },
    {
        "id": 4,
        "type": "positive",
        "icon": "🏆",
        "product": "Samsung QLED Q80C 55\"",
        "title": "Amazon Currently Cheapest!",
        "message": "Amazon is ₹8,000 cheaper than Flipkart for the Samsung QLED Q80C right now. Cashback + no-cost EMI available.",
        "store": "Amazon",
        "time": "2 hr ago",
        "action": "View Deal"
    },
    {
        "id": 5,
        "type": "neutral",
        "icon": "🔔",
        "product": "PS5 Slim · Disc Edition",
        "title": "Your Price Alert Triggered",
        "message": "PS5 Slim has reached your target price of ₹49,990 on Flipkart. You set this alert 23 days ago.",
        "store": "Flipkart",
        "time": "4 hr ago",
        "action": "Buy Now"
    },
    {
        "id": 6,
        "type": "urgent",
        "icon": "⚡",
        "product": "Nike Air Jordan 1 OG",
        "title": "Flash Sale — Ends in 2 Hours!",
        "message": "Nike Air Jordan 1 Retro High OG is 40% off on Amazon for the next 2 hours. Only 7 pairs left in your size.",
        "store": "Amazon",
        "time": "5 min ago",
        "action": "Grab Deal"
    }
]
